config/routes.rb
Rails.application.routes.draw do

  resources :wikis do
    resources :collaborators, only: [:new, :create, :destroy]
  end
  resources :charges, only: [:new, :create]
  resources :downgrade, only: [:new, :create]
  post 'downgrade/create'
  get 'wikis/show'
  get 'wikis/new'
  get 'wikis/edit'
  get 'welcome/about'


  devise_for :users
  delete 'charges/downgrade'

  authenticated :user do
    root 'wikis#index', as: :authenticated_root
  end

  root 'welcome#index'
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
	belongs_to :user
	belongs_to :wiki


	validates :user, presence: true
	validates :role, :admin || :premium, presence: true
  validates :wiki, presence: true
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def create
    @wiki = Wiki.find(params[:wiki_id])
    @user = User.find_by_email(params[:email])
    @collaborator = Collaborator.where(wiki: @wiki, user: @user).first_or_initialize

    if @collaborator.persisted?
      flash[:alert] = "Oops! This collaborator has already been added to this wiki."
    else
      if @collaborator.save
        flash[:notice] = "You have successfully added a collaborator to your wiki."
      else
        flash.now[:alert] = "There was an error adding the collaborator. Please try again."
      end
    end
    redirect_to edit_wiki_path(@wiki)
  end

  def destroy
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = Collaborator.find(params[:id])
    if @collaborator.destroy
      flash[:notice] = "The collaborator was removed from your wiki."
    else
      flash.now[:alert] = "There was an error removing the collaborator."
    end
    redirect_to edit_wiki_path(@wiki)
  end
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/views/collaborators/_form.html.erb
<div class="row">
  <div class="col-md-8">
    <%if current_user.premium? || current_user.admin? %>
      <h3>Add Collaborators</h3>
      <%= form_for [@wiki, Collaborator.new] do |f| %>
        <div class="form-group">
          <%= email_field_tag :email, '', class: 'form-control', placeholder: 'Enter collaborator\'s email' %>
        </div>
        <div class="form-group">
          <%= f.submit "Add Collaborator", class: 'btn btn-success' %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/collaborators/_show.html.erb
<% if @wiki.private? %>
  <div>
    <% if @wiki.collaborators.any? %>
      <h3>Remove Collaborators</h3>
      <% @wiki.collaborators.each do |c| %>
        <h5><%= c.user.email %></h5>
        <%= link_to "Delete", wiki_collaborator_path(@wiki, c), method: :delete, class: 'btn btn-success', data: {confirm: 'Are you sure you want to delete this collaborator?'} %>
      <% end %>
    <% else %>
      <p>No collaborators for this Wiki yet</p>
    <% end %>
  </div>
<% end %>

app/views/collaborators/create.html.erb
<h1>Collaborators#create</h1>
<p>Find me in app/views/collaborators/create.html.erb</p>

app/views/collaborators/destroy.html.erb
<h1>Collaborators#destroy</h1>
<p>Find me in app/views/collaborators/destroy.html.erb</p>

app/views/collaborators/new.html.erb
<% if @wiki.private? %>
  <div>
    <% if @wiki.collaborators.any? %>
      <h3>Remove Collaborators</h3>
      <% @wiki.collaborators.each do |c| %>
        <h5><%= c.user.email %></h5>
        <%= link_to "Delete", wiki_collaborator_path(@wiki, c), method: :delete, class: 'btn btn-success', data: {confirm: 'Are you sure you want to delete this collaborator?'} %>
      <% end %>
    <% else %>
      <p>No collaborators for this Wiki yet</p>
    <% end %>
  </div>
<% end %>