config/routes.rb
Rails.application.routes.draw do

  resources :wikis do
    resources :collaborators, only: [:new, :create, :destroy]
  end
  resources :charges, only: [:new, :create]
  resources :downgrade, only: [:new, :create]
  post 'downgrade/create'
  get 'wikis/show'
  get 'wikis/new'
  get 'wikis/edit'
  get 'welcome/about'


  devise_for :users
  delete 'charges/downgrade'

  authenticated :user do
    root 'wikis#index', as: :authenticated_root
  end

  root 'welcome#index'
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user

  has_many :collaborators
  has_many :users, through: :collaborators

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 5 }, presence: true
  validates :user, presence: true

  def collaborated(user)
     collaborators.where(user_id: user.id).first
   end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :authenticate_user!, except: :index
  after_action :verify_authorized, except: :index


  def index
    @wikis = policy_scope(Wiki)

  end

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user
    authorize @wiki
    if @wiki.save
      flash[:notice] = "Wiki was saved."
       redirect_to @wiki
     else
       flash.now[:alert] = "There was an error saving the wiki. Please try again."
       render :new
     end
   end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    @collaborator = Collaborator.all
    @selected_collaborators = []
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)
    authorize @wiki
    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error updating the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the post."
      render :show
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/wikis/_form.html.erb
<%= form_for wiki do |f| %>
  <% if wiki.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(wiki.errors.count, "error") %>.</h4>
      <ul>
        <% wiki.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
     <%= f.label :title %>
     <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  </div>

  <div class="form-group">
     <%= f.label :body %>
     <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
  </div>

  <% if current_user.admin? || (current_user.premium? && (wiki.user == current_user)) %>
      <div class="form-group">
      <%= f.label :private, class: 'checkbox' do %>
          <%= f.check_box :private %> Private wiki
      <% end %>
      </div>
  <% end %>

  <div class="form-group">
     <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>
<div class="row">
	<div class="col-md-8">
		<%= render partial: 'form', locals: { wiki: @wiki } %>
	</div>
</div>

<% if @wiki.private? %>
	<div class="col-md-4">
		 <%= render partial: 'collaborators/form', locals: { wiki: @wiki } %>

		 <% if Collaborator.exists?(wiki_id: @wiki.id) %>
		 		<%= render partial: 'collaborators/show'%>
		 <% end %>
	</div>
<% end %>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>
<div class="row">
	<div class="col-md-8">
		<% @wikis.each do |wiki| %>
		<% if policy(wiki).show? %>
			<div class="media">
		     <div class="media-body">
		       <h4 class="media-heading">
		         <%= link_to markdown(wiki.title), wiki %>
		       </h4>
					 <small>
      				submitted <%= time_ago_in_words(wiki.created_at) %> ago by <%= wiki.user.username %>
    			 </small>
		     </div>
		  </div>
		<% end %>
		<% end %>
	</div>
</div>
<br />
<% if user_signed_in? %>
	<div class="col-md-4">
		<%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
	</div>
<% end %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for posts</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A".</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>

  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
        <%= f.submit "Save", class: 'btn btn-success' %>
        <% if current_user.admin? || current_user.premium? %>
            <div class="form-group">
            <%= f.label :private, class: 'checkbox' do %>
                <%= f.check_box :private %> Private wiki
            <% end %>
            </div>
        <% end %> 
      </div>
    <% end %>
  </div>
</div>

app/views/wikis/show.html.erb
<h1><%=  markdown(@wiki.title) %></h1>
<h1><%= @wiki.private? %></h1>

<div class="row">
	<div class="col-md-8">
		<p> <%= markdown(@wiki.body) %></p>
	</div>

	<% if @wiki.user = current_user %>
		<div class="col-md-4">
			<%= link_to "Edit Wiki", edit_wiki_path(@wiki), class: 'btn btn-success' %>
			<%= link_to "Delete wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
		</div>
	<% end %>
</div>

<p>
  <strong>Collaborators: </strong>
  <%= render partial: 'collaborators/show' %>
</p>