config/routes.rb
Rails.application.routes.draw do

  resources :wikis do
    resources :collaborators, only: [:new, :create, :destroy]
  end
  resources :charges, only: [:new, :create]
  resources :downgrade, only: [:new, :create]
  post 'downgrade/create'
  get 'wikis/show'
  get 'wikis/new'
  get 'wikis/edit'
  get 'welcome/about'


  devise_for :users
  delete 'charges/downgrade'

  authenticated :user do
    root 'wikis#index', as: :authenticated_root
  end

  root 'welcome#index'
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Blocipedia Membership - #{current_user.email}",
      amount: Amount.default
    }
  end

  def create
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: Amount.default,
      description: "Blocipedia Membership - #{current_user.email}",
      currency: 'usd'
    )

    # current_user.update_attribute(:standard, false)
    current_user.premium!

    flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
    redirect_to root_path

    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path
  end

    def downgrade
    current_user.update_attribute(:role, 'standard')
    current_user.wikis.update_all(private: false)
    flash[:notice] = "You have successfully downgraded your account. Your wikis are now public."
    redirect_to edit_user_registration_path
  end
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <% if current_user.standard? %>
    <h4>Create your own wikis, for a one time $15 upgrade to a Premium account!</h4>
    <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
  <% else %>
    <h4>You already are a Premium Member!</h4>
  <% end %>
<% end %>